# Mod Properties
mod_id=bobbysync
mod_name=Bobby Sync
mod_license=ARR
mod_version=1.0
mod_group_id=com.kukki.bobbysync
mod_authors=_Kukki

# Target Minecraft & NeoForge Versions (1.21.1)
minecraft_version=1.21.1
neoforge_version=21.1.243

# JVM Optimization
org.gradle.jvmargs=-Xmx3G -Dfile.encoding=UTF-8
